"use client";
import { useEffect, useMemo, useState } from "react";
type Product={id:number;name:string;category:string;price:number;old:number;icon:string;color:string;rating:number};
const products:Product[]=[{id:1,name:"Studio ANC Headphones",category:"Electronics",price:8999,old:12499,icon:"🎧",color:"#e6edf3",rating:4.8},{id:2,name:"Everyday Runner Sneakers",category:"Fashion",price:4499,old:6999,icon:"👟",color:"#f5e8e9",rating:4.7},{id:3,name:"Active Smart Watch",category:"Electronics",price:6299,old:9499,icon:"⌚",color:"#e9e8e5",rating:4.9},{id:4,name:"Hydrating Skin Set",category:"Beauty",price:2199,old:3199,icon:"🧴",color:"#faece7",rating:4.6},{id:5,name:"Cloud Cotton Hoodie",category:"Fashion",price:3299,old:4899,icon:"👕",color:"#eee9f4",rating:4.8},{id:6,name:"Brew Mini Coffee Maker",category:"Home",price:5799,old:7999,icon:"☕",color:"#eee7df",rating:4.5},{id:7,name:"Travel Ready Backpack",category:"Travel",price:2899,old:4199,icon:"🎒",color:"#e6eee8",rating:4.7},{id:8,name:"Portable Game Console",category:"Gaming",price:7499,old:9999,icon:"🎮",color:"#e7e9f5",rating:4.9}];
const cats=[['For you','✨'],['Electronics','📱'],['Fashion','👗'],['Beauty','💄'],['Home','🏠'],['Gaming','🎮'],['Travel','✈️']];const money=(n:number)=>`Rs. ${n.toLocaleString()}`;
export default function Home(){
 const[tab,setTab]=useState('Home'),[category,setCategory]=useState('For you'),[query,setQuery]=useState('');const[cart,setCart]=useState<Record<number,number>>({}),[saved,setSaved]=useState<number[]>([]),[selected,setSelected]=useState<Product|null>(null),[toast,setToast]=useState('');
 useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem('ladoo-cart')||'{}'));setSaved(JSON.parse(localStorage.getItem('ladoo-saved')||'[]'))}catch{}if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js')},[]);useEffect(()=>{localStorage.setItem('ladoo-cart',JSON.stringify(cart));localStorage.setItem('ladoo-saved',JSON.stringify(saved))},[cart,saved]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),1800)},add=(id:number)=>{setCart(c=>({...c,[id]:(c[id]||0)+1}));notify('Added to your cart')};const count=Object.values(cart).reduce((a,b)=>a+b,0),total=Object.entries(cart).reduce((s,[id,q])=>s+(products.find(p=>p.id===+id)?.price||0)*q,0);const shown=useMemo(()=>products.filter(p=>(category==='For you'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query]);
 return <main>{toast&&<div className="toast">✓ {toast}</div>}<header className="topbar"><div className="brand">la doo<span>●</span></div><div className="deliver">Deliver to <b>Karachi, PK⌄</b></div><button className="round" aria-label="Notifications" onClick={()=>notify('You’re all caught up!')}>♢<i/></button></header>
 {tab==='Home'&&<><section className="searchWrap"><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search la doo"/><button aria-label="Scan">▥</button></label></section><section className="categories">{cats.map(([c,i])=><button className={category===c?'selected':''} onClick={()=>setCategory(c)} key={c}><b>{i}</b><span>{c}</span></button>)}</section>{category==='For you'&&!query&&<section className="hero"><div><small>LA DOO DAYS</small><h1>Big joy.<br/>Tiny prices.</h1><p>Up to 60% off today&apos;s favourites</p><button onClick={()=>document.getElementById('deals')?.scrollIntoView({behavior:'smooth'})}>Shop the sale <b>→</b></button></div><div className="heroArt"><span>60%</span><b>OFF</b></div><div className="dots">● ○ ○</div></section>}<section className="perkRow"><div>✓<span><b>Free delivery</b><small>Over Rs. 3,000</small></span></div><div>↺<span><b>Easy returns</b><small>Within 15 days</small></span></div><div>♢<span><b>Secure pay</b><small>100% protected</small></span></div></section><section className="sectionHead" id="deals"><div><small>DON&apos;T MISS OUT</small><h2>{query?'Search results':category==='For you'?"Today's best deals":category}</h2></div><button onClick={()=>notify('You’re seeing all deals')}>See all →</button></section><section className="products">{shown.map(p=><ProductCard p={p} key={p.id} saved={saved.includes(p.id)} onSave={()=>setSaved(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])} onOpen={()=>setSelected(p)} onAdd={()=>add(p.id)}/>)}</section>{!shown.length&&<Empty icon="⌕" title="Nothing found" text="Try a different search or category."/>}</>}
 {tab==='Categories'&&<Panel title="Shop categories" subtitle="Everything you love, neatly sorted"><div className="categoryGrid">{cats.slice(1).map(([c,i])=><button onClick={()=>{setCategory(c);setTab('Home')}} key={c}><b>{i}</b><span>{c}</span><small>Explore now →</small></button>)}</div></Panel>}
 {tab==='Wishlist'&&<Panel title="Your wishlist" subtitle={`${saved.length} saved item${saved.length===1?'':'s'}`}><section className="products">{products.filter(p=>saved.includes(p.id)).map(p=><ProductCard p={p} key={p.id} saved onSave={()=>setSaved(s=>s.filter(x=>x!==p.id))} onOpen={()=>setSelected(p)} onAdd={()=>add(p.id)}/>)}</section>{!saved.length&&<Empty icon="♡" title="Save what you love" text="Tap the heart on any item and find it here."/>}</Panel>}
 {tab==='Cart'&&<Panel title="Your cart" subtitle={`${count} item${count===1?'':'s'} ready for checkout`}><div className="cartList">{Object.entries(cart).filter(([,q])=>q>0).map(([id,q])=>{const p=products.find(x=>x.id===+id)!;return <div className="cartItem" key={id}><div style={{background:p.color}}>{p.icon}</div><span><b>{p.name}</b><small>Free delivery • 2–3 days</small><strong>{money(p.price)}</strong></span><aside><button onClick={()=>setCart(c=>({...c,[p.id]:Math.max(0,(c[p.id]||0)-1)}))}>−</button>{q}<button onClick={()=>add(p.id)}>+</button></aside></div>})}</div>{!count?<Empty icon="🛒" title="Your cart is waiting" text="Find something great and add it here."/>:<div className="checkout"><div><span>Subtotal</span><b>{money(total)}</b></div><div><span>Delivery</span><b className="green">FREE</b></div><div className="grand"><span>Total</span><b>{money(total)}</b></div><button onClick={()=>{notify('Order placed — thank you!');setCart({})}}>Secure checkout →</button></div>}</Panel>}
 {tab==='Account'&&<Panel title="Hello, shopper!" subtitle="Manage your la doo experience"><div className="profile"><div>LA</div><span><b>La Doo Shopper</b><small>Sign in to sync your account</small></span><button onClick={()=>notify('Demo sign-in complete')}>Sign in</button></div><div className="menu">{[['▣','My orders','Track, return or buy again'],['⌖','Addresses','Home, work and more'],['♧','Payment methods','Cards and cash on delivery'],['?','Help centre','We’re always here']].map(x=><button key={x[1]} onClick={()=>notify(`${x[1]} opened`)}><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span>›</button>)}</div></Panel>}
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><section className="productSheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="sheetImage" style={{background:selected.color}}>{selected.icon}<i>-{Math.round((1-selected.price/selected.old)*100)}%</i></div><div className="sheetBody"><small>{selected.category.toUpperCase()}</small><h2>{selected.name}</h2><div className="sheetRating">★ {selected.rating} <span>• 120+ verified ratings</span></div><div className="sheetPrice">{money(selected.price)} <del>{money(selected.old)}</del></div><p>Premium quality, carefully selected for la doo shoppers. Includes a 1-year seller warranty and easy 15-day returns.</p><button onClick={()=>{add(selected.id);setSelected(null)}}>Add to cart • {money(selected.price)}</button></div></section></div>}
 <nav className="bottomNav">{[['Home','⌂'],['Categories','▦'],['Wishlist','♡'],['Cart','▱'],['Account','♙']].map(([n,i])=><button key={n} className={tab===n?'active':''} onClick={()=>{setTab(n);if(n==='Home')setCategory('For you')}}>{i}{n==='Cart'&&count>0&&<i>{count}</i>}<span>{n}</span></button>)}</nav></main>}
function ProductCard({p,saved,onSave,onOpen,onAdd}:{p:Product;saved:boolean;onSave:()=>void;onOpen:()=>void;onAdd:()=>void}){return <article className="product"><div className="productImage" style={{background:p.color}} onClick={onOpen}><span>{p.icon}</span><i>-{Math.round((1-p.price/p.old)*100)}%</i><button className={saved?'saved':''} onClick={e=>{e.stopPropagation();onSave()}} aria-label={`Save ${p.name}`}>{saved?'♥':'♡'}</button></div><button className="productInfo" onClick={onOpen}><div className="rating">★ {p.rating} <span>(120+)</span></div><h3>{p.name}</h3><div className="price">{money(p.price)} <del>{money(p.old)}</del></div><p>🚚 Free delivery</p></button><button className="addBtn" onClick={onAdd}>+</button></article>}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="panel"><header><h1>{title}</h1><p>{subtitle}</p></header>{children}</section>}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="empty big"><i>{icon}</i><b>{title}</b><span>{text}</span></div>}
